"""Add image_url to Recipe

Revision ID: 01d88d38ad5b
Revises: bf08b8f6a752
Create Date: 2026-07-30 22:28:56.025871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01d88d38ad5b'
down_revision = 'bf08b8f6a752'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
